version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health
    networks:
      - my-network
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  health-department-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-department-service
    ports:
      - "8082:8083"
    networks:
      - my-network
    depends_on:
      - mysql

networks:
  my-network:
    driver: bridge
